### ISSUE TITLE
Issue #10 needs to be updated. 

### ISSUE THREAD

**Issue by derpmatt** [pop-os/appstream-data#18]
Many of the items on the list in #10 are already in the Pop!_Shop. 
DBeaver
Nextcloud (although it is half done - I have a more complete one ready)
Mailspring (is ready, but already discussed with mmstick)
MakeMKV
Sublime Text
Discord (Is done - although there seems to be some anomalies happening with different users)
Sayonara

All that should be left unchecked is;
Monodevelop
OVMF (which I'm currently working on)
Shortwave

**Comment by jackpot51** [comment]
Updated
